services:
  postgres:
    restart: always
    image: postgres:17
    container_name: postgres_unipile
    volumes:
      - ${HOST_DIR}:/var/lib/postgresql/data
    expose:
      - 5434
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"